<a href="https://colab.research.google.com/github/Sarthak-Rajvaidya/Tensors-in-pytorch-deep-dive/blob/main/Pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Here we will learn about how to train a neural netwrok using pytorch

In [ ]:
# # thepath will be like thesew
# (1)Create the model
# (2)Forward pass
# (3) Loss calculation
# (4)Backprop
# (5)Update parameters

In [8]:
#generate required libraries
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
#Train test split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [9]:
#Scaling
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
X_train

array([[ 1.86305678,  0.48642094,  1.73165505, ...,  0.50492188,
        -1.04505921, -0.69211764],
       [ 1.05718576,  0.32122652,  1.0994939 , ...,  0.61384267,
        -0.68976039, -0.35693985],
       [-1.07837245, -1.63357421, -1.06283214, ..., -0.70160938,
         0.0587358 , -0.36571701],
       ...,
       [-0.44518808,  0.12620532, -0.44825429, ..., -0.55705592,
        -0.33919888, -0.34267696],
       [-0.63514339, -0.63323018, -0.50853985, ...,  1.15844667,
         4.53865918,  1.04850289],
       [ 3.2272813 ,  1.27797758,  3.36438913, ...,  2.71757011,
        -0.86030382,  1.16370311]])

In [11]:
y_train

237    M
156    M
390    B
341    B
538    B
      ..
371    B
133    B
301    B
146    M
82     M
Name: diagnosis, Length: 455, dtype: object

In [12]:
#label encoder for y_test and y_train so text get converted into numericak
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_test

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0])

In [14]:
#Numpy arrays to pytorch tensors
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor =  torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

Defining a model

In [31]:
#lets take apprch of oop

class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bais = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bais
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

Importatant parameters

In [22]:
learning_rate = 0.1
epochs = 1

Training pipeline

In [30]:
# Create model
model = MySimpleNN(X_train_tensor)
model.weights

# Define a loop
for epoch in range(epochs):

    # Forward pass
    y_pred = model.forward(X_train_tensor)
    print(y_pred)

    # Loss calculation
    # Backward pass
    # Parameter updates

tensor([[9.9416e-01],
        [9.9996e-01],
        [2.3962e-05],
        [9.1821e-02],
        [1.4586e-03],
        [1.6713e-02],
        [1.0000e+00],
        [1.0000e+00],
        [9.9672e-01],
        [1.0000e+00],
        [9.9997e-01],
        [9.9987e-01],
        [1.9951e-02],
        [3.4854e-02],
        [9.5198e-01],
        [1.3107e-01],
        [9.4479e-03],
        [9.9568e-05],
        [9.0315e-05],
        [9.6617e-04],
        [9.9961e-01],
        [5.3900e-05],
        [9.9629e-01],
        [9.9625e-01],
        [2.5384e-01],
        [9.4445e-01],
        [9.9999e-01],
        [1.0000e+00],
        [9.9999e-01],
        [9.8684e-01],
        [5.1172e-05],
        [1.0591e-05],
        [1.7996e-02],
        [1.3497e-04],
        [9.1173e-01],
        [1.6028e-06],
        [3.1783e-02],
        [2.9552e-01],
        [8.5892e-04],
        [3.1197e-02],
        [6.5529e-05],
        [4.0588e-03],
        [7.4988e-02],
        [9.9999e-01],
        [4.1118e-05],
        [9.9415e-01],
        [5.5445e-05],
        [2.5291e-02],
        [1.0000e+00],
        [2.3479e-01],
        [1.8031e-03],
        [1.0466e-06],
        [5.8469e-01],
        [1.0000e+00],
        [4.5498e-03],
        [1.0000e+00],
        [6.1948e-02],
        [3.8273e-04],
        [1.0000e+00],
        [1.0698e-05],
        [3.4041e-01],
        [1.0000e+00],
        [1.5803e-04],
        [1.6000e-04],
        [1.0000e+00],
        [9.9771e-01],
        [5.3254e-02],
        [9.8060e-01],
        [9.7286e-01],
        [1.5147e-01],
        [5.9613e-01],
        [8.5794e-01],
        [2.1684e-04],
        [1.5132e-02],
        [1.0000e+00],
        [9.9974e-01],
        [1.0000e+00],
        [9.9991e-01],
        [1.5169e-04],
        [4.7271e-06],
        [9.7169e-07],
        [9.9974e-01],
        [8.0598e-02],
        [1.0000e+00],
        [1.7433e-03],
        [4.6631e-03],
        [8.3164e-04],
        [9.9999e-01],
        [3.5693e-03],
        [9.9999e-01],
        [1.2332e-05],
        [8.6097e-05],
        [9.9990e-01],
        [2.8450e-04],
        [1.0000e+00],
        [9.9999e-01],
        [6.8566e-01],
        [6.8867e-04],
        [4.9095e-01],
        [3.0364e-02],
        [7.3112e-03],
        [1.5407e-04],
        [2.1339e-05],
        [1.0000e+00],
        [1.1698e-02],
        [1.8082e-01],
        [4.6611e-04],
        [2.2181e-03],
        [9.9996e-01],
        [1.5031e-02],
        [2.6066e-03],
        [6.3561e-01],
        [8.7192e-01],
        [8.4961e-07],
        [1.1630e-03],
        [3.1936e-03],
        [2.4844e-03],
        [9.9991e-01],
        [9.7636e-01],
        [3.0735e-05],
        [9.9933e-01],
        [2.4837e-05],
        [1.2305e-03],
        [2.4521e-01],
        [9.6297e-05],
        [9.9998e-01],
        [2.3974e-05],
        [4.5000e-01],
        [1.0000e+00],
        [4.4885e-03],
        [1.1000e-03],
        [6.8379e-02],
        [8.9575e-03],
        [2.6463e-04],
        [1.9713e-02],
        [1.4169e-03],
        [9.7449e-01],
        [1.2634e-02],
        [1.8113e-05],
        [5.9521e-04],
        [1.0000e+00],
        [1.5960e-02],
        [6.5673e-04],
        [1.1928e-03],
        [8.6231e-03],
        [5.0479e-01],
        [1.0000e+00],
        [9.9986e-01],
        [1.5886e-03],
        [1.0000e+00],
        [1.0000e+00],
        [4.5092e-03],
        [1.2717e-03],
        [3.3562e-02],
        [9.9943e-01],
        [9.9897e-01],
        [8.2849e-01],
        [9.9999e-01],
        [9.9910e-01],
        [9.9875e-01],
        [9.9240e-01],
        [9.9998e-01],
        [1.0000e+00],
        [1.7138e-04],
        [5.3027e-04],
        [3.1388e-01],
        [2.2659e-02],
        [1.5949e-06],
        [1.0123e-03],
        [3.0034e-06],
        [4.9355e-03],
        [9.5457e-05],
        [1.4610e-05],
        [1.8956e-03],
        [5.0509e-05],
        [9.9972e-01],
        [9.9100e-01],
        [6.8927e-01],
        [9.9381e-01],
        [7.1263e-01],
        [6.5870e-03],
        [2.9992e-01],
        [1.6070e-02],
        [4.8738e-07],
        [1.0000e+00],
        [8.9191e-06],
        [1.0000e+00],
        [1.0000e+00],
        [5.0373e-05],
        [6.0130e-04],
        [9.9906e-01],
        [9.8449e-01],
        [1.0000e+00],
        [2.5459e-06],
        [9.9282e-01],
        [5.7053e-01],
        [1.8724e-03],
        [1.7164e-03],
        [9.9950e-01],
        [8.0855e-05],
        [2.3536e-01],
        [3.4267e-04],
        [2.0562e-01],
        [9.9999e-01],
        [1.0000e+00],
        [4.4759e-04],
        [1.0000e+00],
        [3.9904e-04],
        [1.0000e+00],
        [1.0905e-02],
        [8.1920e-04],
        [1.9716e-02],
        [5.2163e-04],
        [1.4253e-06],
        [1.0088e-02],
        [1.9853e-01],
        [1.2129e-01],
        [3.1310e-01],
        [2.3400e-04],
        [1.0000e+00],
        [4.8982e-04],
        [1.9466e-04],
        [2.6555e-06],
        [2.3416e-03],
        [1.1584e-02],
        [5.8350e-01],
        [1.0000e+00],
        [2.6192e-05],
        [1.0000e+00],
        [6.0731e-03],
        [9.6090e-01],
        [1.0960e-02],
        [1.0000e+00],
        [8.0636e-03],
        [1.4969e-03],
        [2.3827e-04],
        [9.9944e-01],
        [7.1375e-03],
        [1.4559e-01],
        [2.8222e-05],
        [6.5677e-01],
        [9.9965e-01],
        [1.7905e-04],
        [9.9999e-01],
        [2.3614e-04],
        [9.9975e-01],
        [7.7435e-01],
        [2.4587e-04],
        [9.9997e-01],
        [1.0000e+00],
        [6.2395e-06],
        [9.9904e-01],
        [5.2814e-01],
        [9.9944e-01],
        [2.8161e-01],
        [5.8224e-04],
        [9.9501e-01],
        [9.7659e-06],
        [6.1105e-03],
        [7.4460e-04],
        [2.8722e-04],
        [5.0485e-01],
        [9.5821e-06],
        [6.2883e-02],
        [3.6098e-04],
        [1.8916e-05],
        [5.3105e-01],
        [5.5584e-06],
        [1.0237e-06],
        [6.1063e-06],
        [5.2869e-04],
        [1.0000e+00],
        [1.8783e-04],
        [8.5320e-02],
        [9.9997e-01],
        [1.0000e+00],
        [1.0000e+00],
        [4.1757e-04],
        [1.6064e-01],
        [8.1128e-03],
        [8.0120e-01],
        [9.9876e-01],
        [1.3431e-02],
        [4.5612e-04],
        [6.4375e-04],
        [7.8216e-01],
        [3.8998e-04],
        [9.9632e-01],
        [4.7259e-07],
        [6.2806e-04],
        [9.9985e-01],
        [3.0602e-04],
        [9.9715e-01],
        [9.8891e-01],
        [5.6523e-03],
        [1.0000e+00],
        [2.0901e-04],
        [8.8036e-01],
        [4.9976e-03],
        [3.3747e-03],
        [1.9029e-02],
        [9.3176e-01],
        [3.5201e-07],
        [1.0000e+00],
        [1.8001e-01],
        [3.4546e-04],
        [2.4460e-01],
        [9.9999e-01],
        [1.3711e-03],
        [3.8926e-01],
        [5.0174e-06],
        [2.1304e-02],
        [9.1654e-04],
        [1.0000e+00],
        [6.2589e-03],
        [1.1727e-05],
        [9.9903e-01],
        [9.9977e-01],
        [4.3488e-04],
        [3.1842e-03],
        [9.9886e-01],
        [1.7841e-01],
        [1.0000e+00],
        [3.9847e-01],
        [2.4350e-02],
        [9.8325e-01],
        [1.0000e+00],
        [1.4033e-01],
        [1.3231e-01],
        [8.1738e-04],
        [3.3685e-01],
        [9.9965e-01],
        [9.9970e-01],
        [1.0260e-02],
        [9.9346e-01],
        [2.2795e-05],
        [9.9988e-01],
        [1.7402e-04],
        [9.9899e-01],
        [9.9993e-01],
        [9.8177e-01],
        [1.0000e+00],
        [1.0000e+00],
        [2.9288e-05],
        [5.2177e-02],
        [7.5733e-04],
        [1.6808e-01],
        [1.7078e-05],
        [5.5488e-01],
        [4.0894e-02],
        [1.0000e+00],
        [9.9990e-01],
        [5.8863e-01],
        [1.1257e-05],
        [1.6118e-02],
        [9.8195e-01],
        [5.2588e-03],
        [2.5807e-01],
        [2.3560e-02],
        [1.6125e-03],
        [5.8401e-03],
        [9.9994e-01],
        [4.0112e-04],
        [1.0000e+00],
        [4.0862e-07],
        [3.5381e-04],
        [3.8992e-04],
        [5.4133e-02],
        [8.9453e-01],
        [1.0000e+00],
        [3.0505e-02],
        [3.4184e-02],
        [1.2415e-04],
        [5.2687e-01],
        [9.9136e-01],
        [9.4018e-03],
        [1.5203e-04],
        [3.6212e-01],
        [9.9893e-01],
        [9.9999e-01],
        [9.9599e-01],
        [4.0934e-06],
        [6.5188e-03],
        [9.3273e-01],
        [1.0000e+00],
        [4.5454e-04],
        [2.8676e-04],
        [9.9984e-01],
        [1.0000e+00],
        [1.7608e-04],
        [7.7788e-06],
        [8.8307e-01],
        [1.7117e-06],
        [1.1492e-04],
        [9.4341e-01],
        [1.6781e-05],
        [1.6262e-03],
        [9.1313e-02],
        [1.0000e+00],
        [9.9997e-01],
        [1.0000e+00],
        [9.9998e-01],
        [9.9997e-01],
        [9.9997e-01],
        [9.9541e-01],
        [8.4841e-01],
        [1.9554e-04],
        [9.9235e-01],
        [2.3820e-03],
        [3.9155e-05],
        [1.3853e-05],
        [1.1918e-01],
        [9.7379e-03],
        [5.4019e-04],
        [8.6233e-02],
        [5.1483e-02],
        [1.0000e+00],
        [9.9101e-01],
        [5.0233e-02],
        [4.6909e-01],
        [1.8900e-02],
        [8.0791e-03],
        [1.0000e+00],
        [9.4857e-01],
        [1.3022e-04],
        [9.8529e-01],
        [1.0000e+00],
        [2.1203e-06],
        [9.9846e-01],
        [1.0608e-01],
        [2.8474e-03],
        [1.2327e-06],
        [2.3563e-03],
        [8.7585e-01],
        [5.2095e-05],
        [9.4921e-03],
        [1.6378e-03],
        [6.1778e-01],
        [7.0726e-05],
        [9.9997e-01],
        [8.5039e-04],
        [3.6450e-02],
        [9.9991e-01],
        [1.7513e-02],
        [9.9529e-01],
        [8.0564e-01],
        [2.4652e-02],
        [1.8410e-04],
        [6.6569e-02],
        [1.0000e+00],
        [9.0748e-05],
        [8.9026e-03],
        [3.8817e-02],
        [9.9951e-01],
        [1.0000e+00]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [20]:
model.bais

tensor([0.], dtype=torch.float64, requires_grad=True)